app:
  publicUrl: http://localhost:8082/
  allowRegistrations: true
  googleAnalyticsTrackingCode:
  googleClientId:
  googleClientSecret:
  backgroundThreads: 3
  databaseUpdateThreads: 1
  smtpHost:
  smtpPort:
  smtpTls: false
  smtpUserName:
  smtpPassword:
  heavyLoad: false
  pubsubhubbub: false
  imageProxyEnabled: false
  queryTimeout: 0
  keepStatusDays: 0
  refreshIntervalMinutes: 5
  cache: noop
  announcement:

database:
  driverClass: org.h2.Driver
  user: sa
  password: sa
  url: jdbc:h2:./target/example
  properties:
    charSet: UTF-8
  # hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    maxWaitForConnection: 1s
    validationQuery: "/* MyApplication Health Check */ SELECT 1"
    minSize: 1
    maxSize: 8
    checkConnectionWhileIdle: true
    
server:
  applicationConnectors:
    - type: http
      port: 8083
  adminConnectors:
    - type: http
      port: 8084
logging:
  level: WARN
  loggers:
    com.commafeed: DEBUG
    liquibase: INFO
    org.hibernate.SQL: ALL
  appenders:
    - type: console