# CommaFeed settings
# ------------------
app:
  # url used to access commafeed
  publicUrl: http://localhost:8082/
  
  # wether to allow user registrations
  allowRegistrations: true
  
  # create a demo account the first time the app starts
  createDemoAccount: false
  
  # put your google analytics tracking code here
  googleAnalyticsTrackingCode:
  
  # put your google server key (used for youtube favicon fetching)
  googleAuthKey:
  
  # number of http threads
  backgroundThreads: 3
  
  # number of database updating threads
  databaseUpdateThreads: 1
  
  # settings for sending emails (password recovery)
  smtpHost: localhost
  smtpPort: 25
  smtpTls: false
  smtpUserName: user
  smtpPassword: pass

  # Graphite Metric settings
  # Allows those who use Graphite to have CommaFeed send metrics for graphing (time in seconds)
  graphiteEnabled: false
  graphitePrefix: "test.commafeed"
  graphiteHost: "localhost"
  graphitePort: 2003
  graphiteInterval: 60
  
  # wether this commafeed instance has a lot of feeds to refresh
  # leave this to false in almost all cases
  heavyLoad: false
  
  # minimum amount of time commafeed will wait before refreshing the same feed
  refreshIntervalMinutes: 5
  
  # wether to enable pubsub
  # probably not needed if refreshIntervalMinutes is low
  pubsubhubbub: false
  
  # if enabled, images in feed entries will be proxied through the server instead of accessed directly by the browser
  # useful if commafeed is usually accessed through a restricting proxy  
  imageProxyEnabled: false
  
  # database query timeout (in milliseconds), 0 to disable
  queryTimeout: 0
  
  # time to keep unread statuses (in days), 0 to disable
  keepStatusDays: 0
  
  # entries to keep per feed, old entries will be deleted, 0 to disable
  maxFeedCapacity: 500
  
  # cache service to use, possible values are 'noop' and 'redis'
  cache: noop
  
  # announcement string displayed on the main page
  announcement:
  
# Database connection
# -------------------  
# for MySQL
# driverClass is com.mysql.jdbc.Driver
# url is jdbc:mysql://localhost/commafeed?autoReconnect=true&failOverReadOnly=false&maxReconnects=20&rewriteBatchedStatements=true
#
# for PostgreSQL
# driverClass is org.postgresql.Driver
# url is jdbc:postgresql://localhost:5432/commafeed
#
# for Microsoft SQL Server
# driverClass is net.sourceforge.jtds.jdbc.Driver
# url is jdbc:jtds:sqlserver://localhost:1433/commafeed;instance=<instanceName, remove if not needed>

database:
  driverClass: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost/commafeed?autoReconnect=true&failOverReadOnly=false&maxReconnects=20&rewriteBatchedStatements=true
  user: root
  password:
  properties:
    charSet: UTF-8
  validationQuery: "/* CommaFeed Health Check */ SELECT 1"
    
server:
  applicationConnectors:
    - type: http
      port: 8083
  adminConnectors:
    - type: http
      port: 8084
      
logging:
  level: INFO
  loggers:
    com.commafeed: DEBUG
    liquibase: INFO
    org.hibernate.SQL: INFO # or ALL for sql debugging
    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: WARN
  appenders:
    - type: console
    - type: file
      currentLogFilename: log/commafeed.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: log/commafeed-%d.log
      archivedFileCount: 5
      timeZone: UTC
      
# Redis pool configuration
# (only used if app.cache is 'redis')
# -----------------------------------
redis:
  host: localhost
  port: 6379
  password: 
  timeout: 2000
  database: 0
  maxTotal: 500
   